INFO:django.utils.autoreload:E:\aaexperimental learning\nepller\TwitterClone\Tweets\serializer.py changed, reloading.
INFO:django.utils.autoreload:E:\aaexperimental learning\nepller\TwitterClone\Tweets\models.py changed, reloading.
INFO:django.utils.autoreload:E:\aaexperimental learning\nepller\TwitterClone\Tweets\serializer.py changed, reloading.
ERROR:django.request:Internal Server Error: /signup/
Traceback (most recent call last):
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 100, in Auth
    token = request.session.get('authtoken').get('token')
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\aaexperimental learning\nepller\TwitterClone\Tweets\views.py", line 64, in Timeline
    if is_autherized(request,username):
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 123, in is_autherized
    validation = Auth(request,username)
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 111, in Auth
    except (jwt.ExpiredSignature, jwt.DecodeError, jwt.InvalidTokenError) as e:
AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
INFO:django.utils.autoreload:E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py changed, reloading.
ERROR:django.request:Internal Server Error: /signup/
Traceback (most recent call last):
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 100, in Auth
    token = request.session.get('authtoken').get('token')
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "E:\aaexperimental learning\nepller\TwitterClone\Tweets\views.py", line 64, in Timeline
    if is_autherized(request,username):
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 123, in is_autherized
    validation = Auth(request,username)
  File "E:\aaexperimental learning\nepller\TwitterClone\TUsers\views.py", line 111, in Auth
    except (jwt.ExpiredSignature, jwt.DecodeError, jwt.InvalidTokenError) as e:
AttributeError: module 'jwt' has no attribute 'ExpiredSignature'
